NODE:
  - Name: "Node0"
    ID: 0x00
    clock_prio: 1
    network_address_0: "172.200.0.2"
    network_address_1: "172.200.1.2"

  - Name: "Node1"
    ID: 0x01
    clock_prio: 0
    network_address_0: "172.200.0.3"
    network_address_1: "172.200.1.3"

  - Name: "Node2"
    ID: 0x02
    clock_prio: 2
    network_address_0: "172.200.0.4"
    network_address_1: "172.200.1.4"

APP:
  - Name: "SIM"
    Node: [ "Node2" ]
    State: [ "RUNNING" ]

  - Name: "TST"
    Node: [ "Node2" ]
    State: [ "RUNNING" ]

  - Name: "SFU"
    Node: ["Node1"]
    State: ["RUNNING"]

  - Name: "SHL"
    Node: ["Node2"]
    State: ["RUNNING"]

  - Name: "SAS"
    Node: ["Node2"]
    State: ["RUNNING"]

  - Name: "ANS"
    Node: ["Node2"]
    State: ["RUNNING"]

  - Name: "NAD"
    Node: ["Node2"]
    State: ["RUNNING"]

  - Name: "RPL"
    Node: ["Node1"]
    State: ["RUNNING"]

  - Name: "A01"
    Node: ["Node2"]
    State: ["RUNNING"]

  - Name: "XBR"
    Node: [ "Node2" ]
    State: [ "RUNNING" ]

  - Name: "IMU"
    Node: [ "Node2" ]
    State: [ "RUNNING" ]

  - Name: "AIS"
    Node: [ "Node2" ]
    State: [ "RUNNING" ]

  - Name: "HMI"
    Node: [ "Node2" ]
    State: [ "RUNNING" ]

  - Name: "HMJ"
    Node: [ "Node2" ]
    State: [ "RUNNING" ]

  - Name: "SHP"
    Node: [ "Node2" ]
    State: [ "RUNNING" ]

  - Name: "RUT"
    Node: [ "Node2" ]
    State: [ "RUNNING" ]

  - Name: "APS"
    Node: [ "Node2" ]
    State: [ "RUNNING" ]

  - Name: "ACS"
    Node: [ "Node2" ]
    State: [ "RUNNING" ]

  - Name: "COS"
    Node: [ "Node2" ]
    State: [ "RUNNING" ]

  - Name: "IOS"
    Node: [ "Node2" ]
    State: [ "RUNNING" ]

